In [6]:
#These are all the imports I need
#By: Jesus Plascencia 
# 9/8/2025
# A review of Data 101
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.defaule = 'colab'

In [29]:
#I have to det the path to data or else it does know where the data is
#0] Read in the .csv file and display it

DF = pd.read_csv("data/lego-sales.csv")
#Displaying it

DF.head(20)
#print(DF)

,first_name,last_name,age,phone_number,set_id,number,theme,subtheme,year,name,pieces,us_price,image_url,quantity
0,Kimberly,Beckstead,24,216-555-2549,24701,76062,DC Comics Super Heroes,Mighty Micros,2018,Robin vs. Bane,77.0,9.99,http://images.brickset.com/sets/images/76062-1...,1
1,Neel,Garvin,35,819-555-3189,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
2,Neel,Garvin,35,819-555-3189,24665,21031,Architecture,NaN,2018,Burj Khalifa,333.0,39.99,http://images.brickset.com/sets/images/21031-1...,1
3,Chelsea,Bouchard,41,NaN,24695,31048,Creator,NaN,2018,Lakeside Lodge,368.0,29.99,http://images.brickset.com/sets/images/31048-1...,1
4,Chelsea,Bouchard,41,NaN,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
5,Chelsea,Bouchard,41,NaN,24721,10831,Duplo,NaN,2018,My First Caterpillar,19.0,9.99,http://images.brickset.com/sets/images/10831-1...,1
6,Bryanna,Welsh,19,NaN,24797,75138,Star Wars,Episode V,2018,Hoth Attack,233.0,24.99,http://images.brickset.com/sets/images/75138-1...,1
7,Bryanna,Welsh,19,NaN,24701,76062,DC Comics Super Heroes,Mighty Micros,2018,Robin vs. Bane,77.0,9.99,http://images.brickset.com/sets/images/76062-1...,3
8,Caleb,Garcia-Wideman,37,907-555-9236,24730,41115,Friends,NaN,2018,Emma's Creative Workshop,108.0,9.99,http://images.brickset.com/sets/images/41115-1...,1
9,Caleb,Garcia-Wideman,37,907-555-9236,25611,21127,Minecraft,Minifig-scale,2018,The Fortress,NaN,109.99,http://images.brickset.com/sets/images/21127-1...,2
10,Chase,Fortenberry,19,205-555-3704,24707,10801,Duplo,NaN,2018,Baby Animals,13.0,9.99,http://images.brickset.com/sets/images/10801-1...,1
11,Chase,Fortenberry,19,205-555-3704,24713,10809,Duplo,NaN,2018,Police Patrol,15.0,14.99,http://images.brickset.com/sets/images/10809-1...,1
12,Kevin,Cruz,20,947-555-7946,24767,70335,Nexo Knights,Ultimate,2018,Ultimate Lavaria,69.0,9.99,http://images.brickset.com/sets/images/70335-1...,2
13,Connor,Brown,36,516-555-4310,24548,71230,Dimensions,Fun Pack,2018,Fun Pack: Doc Brown,69.0,14.99,http://images.brickset.com/sets/images/71230-1...,1
14,Connor,Brown,36,516-555-4310,24913,60112,City,Fire,2018,Fire Engine,376.0,49.99,http://images.brickset.com/sets/images/60112-1...,1
15,Connor,Brown,36,516-555-4310,26034,41573,Mixels,Series 9,2018,Sweepz,61.0,4.99,NaN,1
16,Toni,Borison,40,284-555-4560,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
17,Toni,Borison,40,284-555-4560,24994,10251,Advanced Models,Modular Buildings,2018,Brick Bank,2380.0,169.99,http://images.brickset.com/sets/images/10251-1...,1
18,Daniel,Hurst,44,251-555-0845,24903,41558,Mixels,Series 7,2018,Mixadel,63.0,4.99,http://images.brickset.com/sets/images/41558-1...,1
19,Daniel,Hurst,44,251-555-0845,24695,31048,Creator,NaN,2018,Lakeside Lodge,368.0,29.99,http://images.brickset.com/sets/images/31048-1...,1

14

In [19]:
DF.shape

(620, 14)

In [20]:
DF.dtypes

first_name       object
last_name        object
age               int64
phone_number     object
set_id            int64
number           object
theme            object
subtheme         object
year              int64
name             object
pieces          float64
us_price        float64
image_url        object
quantity          int64
dtype: object

In [21]:
DF.describe()

              age        set_id    year       pieces    us_price    quantity
count  620.000000    620.000000   620.0   551.000000  620.000000  620.000000
mean    34.356452  25124.982258  2018.0   254.206897   29.041613    1.437097
std     11.276537    506.760720     0.0   357.738804   34.630623    0.712849
min     16.000000  24548.000000  2018.0    13.000000    3.990000    1.000000
25%     25.000000  24724.750000  2018.0    70.000000    9.990000    1.000000
50%     33.000000  24804.500000  2018.0   114.000000   19.990000    1.000000
75%     41.000000  25640.250000  2018.0   313.000000   29.990000    2.000000
max     68.000000  26060.000000  2018.0  4634.000000  349.990000    5.000000

In [31]:
#0] Describe what you see in the data set. 

#After Interacting with the data in the dataframe I know that there are 13 variables. These variables range
#from first, last name, age, phone number, theme, year, pieces, US_price, quantity, and so on. There are 
#a total of 620 observations that we can get using the len function, shape function, or describe function. 
#Id also like to note that the max age of participants is 68, and the min is 16. The mean is 34 so this means we
#have data that predominately consist of middle aged indiviudals. Even if we look at the 75th percentile of 
#our data we see that 68 may be an outlier skewing our results.

len(DF.columns)
DF.columns
len(DF)

620

In [39]:
#2] Three most common first names of purchasers
focal_column = "first_name"
top_3_names = DF[focal_column].value_counts().head(3)
print(f"In this same, the first three common names of purchasers are: {top_3_names}")

In this same, the first three common names of purchasers are: first_name
Jackson    13
Jacob      11
Joseph     11
Name: count, dtype: int64

In [40]:
DF.columns

Index(['first_name', 'last_name', 'age', 'phone_number', 'set_id', 'number',
       'theme', 'subtheme', 'year', 'name', 'pieces', 'us_price', 'image_url',
       'quantity'],
      dtype='object')

In [47]:
#3] Three most comon themes of lego sets purchased
focal_column_2 = "theme"
top_3_theme = DF[focal_column_2].value_counts().head(3)
print(f"In this same, the first three common themes of legos are: {top_3_theme}")

In this same, the first three common themes of legos are: theme
Star Wars       75
Nexo Knights    64
Mixels          55
Name: count, dtype: int64

In [49]:

#common_theme = DF['theme','subtheme'].groupby('theme').sum().sort_values(top_3_theme)