In [4]:
#These are all the imports I need
#By: Jesus Plascencia 
# 9/8/2025
# A review of Data 101
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.defaule = 'colab'

In [6]:
#I have to det the path to data or else it does know where the data is
#0] Read in the .csv file and display it

DF = pd.read_csv("data/lego-sales.csv")
#Displaying it

DF.head(20)
#print(DF)

,first_name,last_name,age,phone_number,set_id,number,theme,subtheme,year,name,pieces,us_price,image_url,quantity
0,Kimberly,Beckstead,24,216-555-2549,24701,76062,DC Comics Super Heroes,Mighty Micros,2018,Robin vs. Bane,77.0,9.99,http://images.brickset.com/sets/images/76062-1...,1
1,Neel,Garvin,35,819-555-3189,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
2,Neel,Garvin,35,819-555-3189,24665,21031,Architecture,NaN,2018,Burj Khalifa,333.0,39.99,http://images.brickset.com/sets/images/21031-1...,1
3,Chelsea,Bouchard,41,NaN,24695,31048,Creator,NaN,2018,Lakeside Lodge,368.0,29.99,http://images.brickset.com/sets/images/31048-1...,1
4,Chelsea,Bouchard,41,NaN,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
5,Chelsea,Bouchard,41,NaN,24721,10831,Duplo,NaN,2018,My First Caterpillar,19.0,9.99,http://images.brickset.com/sets/images/10831-1...,1
6,Bryanna,Welsh,19,NaN,24797,75138,Star Wars,Episode V,2018,Hoth Attack,233.0,24.99,http://images.brickset.com/sets/images/75138-1...,1
7,Bryanna,Welsh,19,NaN,24701,76062,DC Comics Super Heroes,Mighty Micros,2018,Robin vs. Bane,77.0,9.99,http://images.brickset.com/sets/images/76062-1...,3
8,Caleb,Garcia-Wideman,37,907-555-9236,24730,41115,Friends,NaN,2018,Emma's Creative Workshop,108.0,9.99,http://images.brickset.com/sets/images/41115-1...,1
9,Caleb,Garcia-Wideman,37,907-555-9236,25611,21127,Minecraft,Minifig-scale,2018,The Fortress,NaN,109.99,http://images.brickset.com/sets/images/21127-1...,2
10,Chase,Fortenberry,19,205-555-3704,24707,10801,Duplo,NaN,2018,Baby Animals,13.0,9.99,http://images.brickset.com/sets/images/10801-1...,1
11,Chase,Fortenberry,19,205-555-3704,24713,10809,Duplo,NaN,2018,Police Patrol,15.0,14.99,http://images.brickset.com/sets/images/10809-1...,1
12,Kevin,Cruz,20,947-555-7946,24767,70335,Nexo Knights,Ultimate,2018,Ultimate Lavaria,69.0,9.99,http://images.brickset.com/sets/images/70335-1...,2
13,Connor,Brown,36,516-555-4310,24548,71230,Dimensions,Fun Pack,2018,Fun Pack: Doc Brown,69.0,14.99,http://images.brickset.com/sets/images/71230-1...,1
14,Connor,Brown,36,516-555-4310,24913,60112,City,Fire,2018,Fire Engine,376.0,49.99,http://images.brickset.com/sets/images/60112-1...,1
15,Connor,Brown,36,516-555-4310,26034,41573,Mixels,Series 9,2018,Sweepz,61.0,4.99,NaN,1
16,Toni,Borison,40,284-555-4560,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1
17,Toni,Borison,40,284-555-4560,24994,10251,Advanced Models,Modular Buildings,2018,Brick Bank,2380.0,169.99,http://images.brickset.com/sets/images/10251-1...,1
18,Daniel,Hurst,44,251-555-0845,24903,41558,Mixels,Series 7,2018,Mixadel,63.0,4.99,http://images.brickset.com/sets/images/41558-1...,1
19,Daniel,Hurst,44,251-555-0845,24695,31048,Creator,NaN,2018,Lakeside Lodge,368.0,29.99,http://images.brickset.com/sets/images/31048-1...,1

In [9]:
DF.shape

(620, 14)

In [11]:
DF.dtypes

first_name       object
last_name        object
age               int64
phone_number     object
set_id            int64
number           object
theme            object
subtheme         object
year              int64
name             object
pieces          float64
us_price        float64
image_url        object
quantity          int64
dtype: object

In [13]:
DF.describe()

              age        set_id    year       pieces    us_price    quantity
count  620.000000    620.000000   620.0   551.000000  620.000000  620.000000
mean    34.356452  25124.982258  2018.0   254.206897   29.041613    1.437097
std     11.276537    506.760720     0.0   357.738804   34.630623    0.712849
min     16.000000  24548.000000  2018.0    13.000000    3.990000    1.000000
25%     25.000000  24724.750000  2018.0    70.000000    9.990000    1.000000
50%     33.000000  24804.500000  2018.0   114.000000   19.990000    1.000000
75%     41.000000  25640.250000  2018.0   313.000000   29.990000    2.000000
max     68.000000  26060.000000  2018.0  4634.000000  349.990000    5.000000

In [15]:
#0] Describe what you see in the data set. 

#After Interacting with the data in the dataframe I know that there are 13 variables. These variables range
#from first, last name, age, phone number, theme, year, pieces, US_price, quantity, and so on. There are 
#a total of 620 observations that we can get using the len function, shape function, or describe function. 
#Id also like to note that the max age of participants is 68, and the min is 16. The mean is 34 so this means we
#have data that predominately consist of middle aged indiviudals. Even if we look at the 75th percentile of 
#our data we see that 68 may be an outlier skewing our results.

len(DF.columns)
DF.columns
len(DF)

620

In [17]:
#2] Three most common first names of purchasers
focal_column = "first_name"
top_3_names = DF[focal_column].value_counts().head(3)
print(f"In this same, the first three common names of purchasers are: {top_3_names}")

In this same, the first three common names of purchasers are: first_name
Jackson    13
Joseph     11
Jacob      11
Name: count, dtype: int64

In [19]:
DF.columns

Index(['first_name', 'last_name', 'age', 'phone_number', 'set_id', 'number',
       'theme', 'subtheme', 'year', 'name', 'pieces', 'us_price', 'image_url',
       'quantity'],
      dtype='object')

In [170]:
#3] Three most comon themes of lego sets purchased
focal_column_2 = "theme"
top_3_theme = DF[focal_column_2].value_counts().head(3)
print(f"The three most common themes of legos are: {top_3_theme}")

The three most common themes of legos are: theme
Star Wars       75
Nexo Knights    64
Gear            55
Name: count, dtype: int64

,first_name,last_name,age,phone_number,set_id,number,theme,subtheme,year,name,pieces,us_price,image_url,quantity
6,Bryanna,Welsh,19,NaN,24797,75138,Star Wars,Episode V,2018,Hoth Attack,233.0,24.99,http://images.brickset.com/sets/images/75138-1...,1
12,Kevin,Cruz,20,947-555-7946,24767,70335,Nexo Knights,Ultimate,2018,Ultimate Lavaria,69.0,9.99,http://images.brickset.com/sets/images/70335-1...,2
20,Judith,Webb,39,917-555-7417,26058,5005059,Gear,Video Games/PS3,2018,Marvel Avengers PS3 Video Game,NaN,49.99,http://images.brickset.com/sets/images/5005059...,2
21,Nicholas,Belfageoua,46,606-555-4814,25881,853549,Gear,Key Chains/Friends,2018,Mia Key Chain,NaN,5.99,http://images.brickset.com/sets/images/853549-...,1
22,Nicholas,Belfageoua,46,606-555-4814,25642,70327,Nexo Knights,NaN,2018,The King's Mech,375.0,29.99,http://images.brickset.com/sets/images/70327-1...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,Miles,Hill,34,NaN,24758,70312,Nexo Knights,NaN,2018,Lance's Mecha Horse,237.0,19.99,http://images.brickset.com/sets/images/70312-1...,2
611,Natalia,Vonduyke,16,859-555-3818,25879,853534,Gear,Key Chains/Ninjago,2018,Airjitzu Jay Key Chain,NaN,5.99,http://images.brickset.com/sets/images/853534-...,2
613,Natalia,Vonduyke,16,859-555-3818,24765,70332,Nexo Knights,Ultimate,2018,Ultimate Aaron,82.0,9.99,http://images.brickset.com/sets/images/70332-1...,1
614,Natalia,Vonduyke,16,859-555-3818,25922,75149,Star Wars,The Force Awakens,2018,Resistance X-wing Fighter,740.0,79.99,http://images.brickset.com/sets/images/75149-1...,1
617,Spencer,Morgan,28,784-555-3455,26060,5005051,Gear,Digital Media,2018,Friends of Heartlake City Girlz 4 Life,NaN,19.99,NaN,1

In [168]:
#4 Among the most common theme of Lego sets purchased, what is the most common subtheme?
#I couldn't use == method so i decided to convert my dataframe into a booleon statement using isin. 
filtered_DF = DF[DF['theme'].isin( top_3_theme.index)]
top_3_subtheme = filtered_DF['subtheme'].head(3)
#filtered_DF
subtheme_list = list(top_3_subtheme)
print(f"The three most common subthemes of legos are: {subtheme_list}")

#common_theme = DF['theme','subtheme'].groupby('theme').sum().sort_values(top_3_theme)

The three most common subthemes of legos are: ['Episode V', 'Ultimate', 'Video Games/PS3']

In [425]:
#5 create data frames for each of the ages in the folloiwing categories. Use masks 

#18 and under
neccessary_column = "age"
mask_18_below = DF[neccessary_column] <= 18
DF_under_18 = DF[mask_18_below]

#19-25
neccessary_column = "age"
mask_25_below = (DF[neccessary_column] >= 19) & (DF[neccessary_column] <= 25)  #Jesus remember --> and fxn does not work with pandas use & 
DF_19_25 = DF[mask_25_below]

#26 - 35
neccessary_column = "age"
mask_26_35 = (DF[neccessary_column] >= 26) & (DF[neccessary_column] <= 35)  
DF_26_35 = DF[mask_26_35]

#36-50
neccessary_column = "age"
mask__36_50 = (DF[neccessary_column] >= 36) & (DF[neccessary_column] <= 50)  
DF_36_50 = DF[mask__36_50]

#51 and over
neccessary_column = "age"
mask_51_over = DF[neccessary_column] <= 51
DF_51_over = DF[mask_51_over]

In [427]:
#6.  Which age group has purchased the highest number of Lego sets.

DF.columns

group_quantity = {
    '18_and_under': DF_under_18['quantity'].sum(), 
    '19_and_25': DF_19_25['quantity'].sum(), 
    '26_and_35': DF_26_35['quantity'].sum(),
    '36_and_50': DF_36_50['quantity'].sum(), 
    '51_and_over': DF_51_over['quantity'].sum(),
}
quant = list(group_quantity.values())
group = list(group_quantity.keys())

max_quant = max(valus)

for i in range(len(quant)): 
    if quant[i] == max_quant: 
        print(f"The age who purchased the highest amount of lego sets is {group[i]} who purchased {quant[i]} legos")

The age who purchased the highest amount of lego sets is 51_and_over who purchased 811 legos

In [437]:
#7.  Which age group has spent the most money on Legos?
DF['money_spent'] = DF['quantity'] * DF ['us_price']

group_spent = {
    '18_and_under_cash': DF_under_18['money_spent'].sum(), 
    '19_and_25_cash': DF_19_25['money_spent'].sum(), 
    '26_and_35_cash': DF_26_35['total_spent'].sum(),
    '36_and_50_cash': DF_36_50['total_spent'].sum(), 
    '51_and_over_cash': DF_51_over['total_spent'].sum(),
}
quant_money = list(group_spent.values())
group_age = list(group_spent.keys())

max_money = max(valus)

for i in range(len(quant_money)): 
    if quant[i] == max_money: 
        print(f"The age who purchased the highest amount of lego sets is {group_age[i]} who purchased ${quant_money[i]} worth of legos")

The age who purchased the highest amount of lego sets is 51_and_over_cash who purchased $23341.89 worth of legos

In [465]:
#8  Which Lego theme has made the most money for Lego?
focal_column_2 = ['theme', 'money_spent'] 

highest_theme = DF[focal_column_2].groupby('theme').sum().sort_values('money_spent', ascending=False).head(1)
highest_theme

print(f"The lego theme that made the most money for lego is {highest_theme}")

The lego theme that made the most money for lego is            money_spent
theme
Star Wars      4447.83

In [467]:
#9.  Which area code has spent the most money on Legos? In the US the area code is the first 3 digits of a phone number. 
#Then using a for loop calculate the average money spent per customer for each area code.

DF

,first_name,last_name,age,phone_number,set_id,number,theme,subtheme,year,name,pieces,us_price,image_url,quantity,money_spent,total_spent,total
0,Kimberly,Beckstead,24,216-555-2549,24701,76062,DC Comics Super Heroes,Mighty Micros,2018,Robin vs. Bane,77.0,9.99,http://images.brickset.com/sets/images/76062-1...,1,9.99,9.99,9.99
1,Neel,Garvin,35,819-555-3189,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1,119.99,119.99,119.99
2,Neel,Garvin,35,819-555-3189,24665,21031,Architecture,NaN,2018,Burj Khalifa,333.0,39.99,http://images.brickset.com/sets/images/21031-1...,1,39.99,39.99,39.99
3,Chelsea,Bouchard,41,NaN,24695,31048,Creator,NaN,2018,Lakeside Lodge,368.0,29.99,http://images.brickset.com/sets/images/31048-1...,1,29.99,29.99,29.99
4,Chelsea,Bouchard,41,NaN,25626,70595,Ninjago,Rise of the Villains,2018,Ultra Stealth Raider,1093.0,119.99,http://images.brickset.com/sets/images/70595-1...,1,119.99,119.99,119.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,Talise,Nieukirk,16,801-555-2343,24902,41556,Mixels,Series 7,2018,Tiketz,62.0,4.99,http://images.brickset.com/sets/images/41556-1...,2,9.98,9.98,9.98
616,Spencer,Morgan,28,784-555-3455,26041,41580,Mixels,Series 9,2018,Myke,63.0,4.99,NaN,2,9.98,9.98,9.98
617,Spencer,Morgan,28,784-555-3455,26060,5005051,Gear,Digital Media,2018,Friends of Heartlake City Girlz 4 Life,NaN,19.99,NaN,1,19.99,19.99,19.99
618,Amelia,Hageman,40,336-555-1950,24702,76063,DC Comics Super Heroes,Mighty Micros,2018,The Flash vs. Captain Cold,88.0,9.99,http://images.brickset.com/sets/images/76063-1...,2,19.98,19.98,19.98
619,Amelia,Hageman,40,336-555-1950,24720,10830,Duplo,NaN,2018,Minnie's Café,27.0,19.99,http://images.brickset.com/sets/images/10830-1...,4,79.96,79.96,79.96

In [ ]:

#10.  Come up with a question you want to answer using these data, and write it down. Then,
#create a data visualization that answers the question, and explain how your visualization answers the question.